# Generated by Django 4.1.1 on 2022-09-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
