# Generated by Django 4.1.1 on 2022-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="avatar.png", upload_to="profile_pics"
            ),
        ),
    ]
